print("This is a BMI Calculator!")
height = float(input("Please enter your height in meters: "))
weight = float(input("Please enter your weight in kg: "))
bmi = weight / (height**2)
print("Your BMI is", bmi)